version: '3.8'

services:
  adaptation-admin:
    image: adaptation-admin
    ports:
      - "3004:80"
    networks:
      - hr-network

  adaptation-server:
    image: adaptation-server
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=your-super-secret-key-with-at-least-32-characters
      - Jwt__Issuer=adaptation-server
      - Jwt__Audience=adaptation-client
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge 