version: '3.8'

services:
  adaptationserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=adaptation;User Id=postgres;Password=postgres;
      - Jwt__Key=your-super-secret-key-with-at-least-32-characters
      - Jwt__Issuer=adaptation-server
      - Jwt__Audience=adaptation-client
    depends_on:
      - db
    networks:
      - adaptation-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adaptation
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adaptation-network

networks:
  adaptation-network:
    driver: bridge

volumes:
  postgres-data: 